steps:
  # Step 1: build app binary.
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=gif-maker"]
    args: ["install", "."]
    id: "go-install"

  # Step 2: package binary as a container.
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/gif-maker:0.0.1-dev", "."]
    id: "docker-build"

images: ["gcr.io/${PROJECT_ID}/gif-maker:0.0.1-dev"]
